<?php

namespace ACF_Multiforms_Example;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Utils {
	/**
	 * Search by key name in multidimensional array
	 */
	public static function search_by_key( $array, $key ) {
		$results = array();

		if ( is_array( $array ) ) {
			if ( isset( $array[$key ] ) ) {
				$results[] = $array[ $key ];
			}

			foreach ( $array as $subarray ) {
				$results = array_merge( $results, self::search_by_key( $subarray, $key ) );
			}
		}

		return $results;
	}

	/**
	* Get ACF $_POST value from a field slug (instead of unique key generated by ACF)
	*/
	public static function get_acf_post_value( $slug = false, $array = null ) {
		if ( is_null( $array ) ) $array = $_POST['acf'];

		$key = acf_get_field( $slug )['key'];
		$results = self::search_by_key( $array, $key );

		if ( count( $results ) === 1 ) {
			return reset( $results );
		}

		return $results;
	}

	/**
	 * Write in debug log
	 */
	public static function debug( $log ) {
		if ( true === WP_DEBUG ) {
			error_log('--------------------------------- /!\ ' . __NAMESPACE__ . ' /!\ --------------------------------- ');
			if ( is_array( $log ) || is_object( $log ) ) error_log( print_r( $log, true ) );
			else error_log( $log );
			error_log('--------------------------------- /!\ ' . __NAMESPACE__ . ' /!\ --------------------------------- ');
		}
	}
}
